http://localhost:8080/products

###

http://localhost:8080/products/1

###

http://localhost:8080/products/0/save?name=forth&price=1500

###

http://localhost:8080/products/1/save?name=forth&price=600

###

http://localhost:8080/products/2/remove









