GET http://localhost:8080/products

###

GET http://localhost:8080/products/1

###

GET http://localhost:8080/products/search?model=mountain

###

GET http://localhost:8080/products/search?model=child

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "id": 0,
  "model": "child",
  "picture": "noavatar.jpg",
  "brand": "Novatrack Maple 16",
  "wheelDiameter": 16,
  "price": 9600,
  "quantity": 5
}

###

PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "model": "comfortable",
  "picture": "noavatar.jpg",
  "brand": "Forward Parma 28",
  "wheelDiameter": 23,
  "price": 17000,
  "quantity": 10
}

###

DELETE http://localhost:8080/products/2

###

GET http://localhost:8080/buyers

###

GET http://localhost:8080/buyers/1

###

GET http://localhost:8080/buyers/6

###

GET http://localhost:8080/buyers/7


###

POST http://localhost:8080/buyers
Content-Type: application/json

{
  "name": "Anna",
  "avatar": "noavatar.jpg",
  "gender": "women",
  "age": 36,
  "phoneNumber": "89378780090"
}

###

PUT http://localhost:8080/buyers
Content-Type: application/json

{
  "id": 1,
  "name": "John",
  "avatar": "noavatar.jpg",
  "gender": "man",
  "age": 30,
  "phoneNumber": "89370883234"
}












